services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: goderpad-backend
    ports:
      - "7778:7778"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      args:
        VITE_API_URL: http://localhost:7778
    container_name: goderpad-frontend
    ports:
      - "7777:7777"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
